### ISSUE TITLE
random erasure CPG value but  accuracy (MAE) becomes better

### ISSUE THREAD

**Issue by QuJing785464** [NuttyLogic/EpigeneticPacemaker#17]
I did a simple test with EP model that training by GSE74193,  and then test in other datasets (such as GSE41169, GSE36064... also in GSE74193) which random erasure CPG value by number 0.5 in a certain proportion  such as 10%, 20% ... 90%. I found that the prediction accuracy (MAE) becomes better with the increase of coverd ratio. I'm perplexed and expect a reasonable explaination. Thanks for your help.

**Comment by NuttyLogic** [comment]
It's possible for the model to improve if variation not associated the trait of interest is removed. The model is robust to site masking in my tests. Could you provide more detail about your model, number of site, etc?

**Comment by QuJing785464** [comment]
The model was trained only on the 'example_data' (in this repository, GEO accession is GSE74193), and then was saved for testing other datasets. The model has 204 sites, which were obtained by calculating Pearson correlation coefficient and selecting with absolute values greater than 0.85. The model can fit well on the training dataset, but the performance on other datasets for testing is not good. I found the EPM algorithm sets a baseline age value (38 years old) and maybe that is why the model is improving with the higher masking, that is the age distribution of the test data are concentrated around 38 years old.

**Comment by NuttyLogic** [comment]
Your explanation makes sense, with fewer sites the model is probably over fitting. The original version of the EPM is highly sensitive to site to site variation. We have a [pre-print](https://www.biorxiv.org/content/10.1101/2023.01.24.525448v1) on a multidimensional model that can account for covariates, which should offer better performance with fewer sites.

**Comment by QuJing785464** [comment]
OK, I will try.
